# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Ansatz
tagline:          'blog'
description:      'fuzzy heuristic guesstimation'
url:              https://pabloriera.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Pablo Riera
  url:            https://pablo-riera.com.ar

paginate:         5
future:           true
# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
#  - icon:         twitter
#    url:          https://twitter.com/iancamporez
#    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/pabloriera
    desc:         Fork me on github

#  - icon:         googleplus-alt
#    url:          https://google.com/+IanCamporezBrunelli
#    desc:         Add me on google+

#  - icon:         feed
#    url:          http://camporez.github.io/atom.xml
#    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Pablo E. Riera
  url:            https://pabloriera.github.io
  type_title:     Theme by https://github.com/camporez/Thinny
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
gems: [jekyll-paginate]